In [6]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

current_font_list= matplotlib.rcParams['font.family']

font_path ="C:\Windows\Fonts\GULIM.TTC"
kfont = matplotlib.font_manager.FontProperties(fname= font_path).get_name()
matplotlib.rcParams['font.family'] = [kfont] + current_font_list

pd_data = pd.read_csv('이륜차신고현황_시도별_20230309173125.csv', encoding='cp949', header = 1)
pd_data

,시도명(1),시군구(1),시점,소계,경형,소형,중형,대형,소계.1,경형.1,소형.1,중형.1,대형.1,소계.2,경형.2,소형.2,중형.2,대형.2
0,부산,금정구,2021.01,8393,382,2271,5315,425,98,12,8,75,3,8295,370,2263,5240,422
1,부산,금정구,2021.02,8398,383,2271,5310,434,98,12,8,75,3,8300,371,2263,5235,431
2,부산,금정구,2021.03,8424,385,2262,5345,432,97,12,8,74,3,8327,373,2254,5271,429
3,부산,금정구,2021.04,8475,398,2280,5345,452,97,12,8,74,3,8378,386,2272,5271,449
4,부산,금정구,2021.05,8499,392,2284,5370,453,96,12,8,74,2,8403,380,2276,5296,451
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,부산,해운대구,2022.09,12817,544,2951,8011,1311,95,7,2,85,1,12722,537,2949,7926,1310
346,부산,해운대구,2022.10,12851,550,2950,8025,1326,95,7,2,85,1,12756,543,2948,7940,1325
347,부산,해운대구,2022.11,12828,542,2941,8027,1318,96,7,2,86,1,12732,535,2939,7941,1317
348,부산,해운대구,2022.12,12802,543,2943,7987,1329,96,7,2,86,1,12706,536,2941,7901,1328
349,부산,해운대구,2023.01,12791,544,2926,7988,1333,96,7,2,86,1,12695,537,2924,7902,1332

In [ ]:
for i in range(3):